### ISSUE TITLE
运行完mananger报错

### ISSUE THREAD

**Issue by weidong7777777** [ody5sey/Voyager#14]
![1](https://user-images.githubusercontent.com/50541718/76138377-494cb400-6082-11ea-8e7e-880f225bf1e3.png)
(Desktop) root@kali:~/Desktop# python3 manager.py
Traceback (most recent call last):
  File "manager.py", line 1, in <module>
    from app import create_app
  File "/root/Desktop/app/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
(Desktop) root@kali:~/Desktop# python manager.py
Traceback (most recent call last):
  File "manager.py", line 1, in <module>
    from app import create_app
  File "/root/Desktop/app/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by ody5sey** [comment]
请下载最新镜像重新安装

**Comment by weidong7777777** [comment]
漏扫的攻击目标不能填东西

**Comment by ody5sey** [comment]
漏洞扫描的数据只能从端口扫描或者是指纹识别那儿继承到，不能单独填写

**Comment by weidong7777777** [comment]
emmm 我端口扫描里边有目标 但是漏扫还是不能用

**Comment by ody5sey** [comment]
请截图，如果认为是BUG，请按照git issues的bug模版提交数据
