### ISSUE TITLE
代码里很多的module无法加载先是flask，然后是asiic码的什么

### ISSUE THREAD

**Issue by new4u** [ody5sey/Voyager#18]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）

**Bug描述**
清晰而简洁的Bug描述（必写）
ModuleNotFoundError: No module named 'flask'

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
kali linux 2020-vmware-amd64
 - Python版本：[例如3.8.1]（必写）
3.8.1

 
**如何复现**
复现步骤（必写,请提交web界面截图和console截图）
`(Voyager) kali@kali:/usr/Voyager$ python manager.py
Traceback (most recent call last):
  File "manager.py", line 1, in <module>
    from app import create_app
  File "/usr/Voyager/app/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'`

**报错文本**
复制完整的报错文本（必写）
如上

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）
能使用软件
**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**Comment by ody5sey** [comment]
是否采用最新代码，不是的话请全新下载安装

**Comment by new4u** [comment]
是直接从git上直接clone然后按照Readme安装出现的问题，一共尝试了3次 。
git clone https://github.com/ody5sey/Voyager.git

**Comment by ody5sey** [comment]
是今天克隆的吗

**Comment by ody5sey** [comment]
是按照这个流程执行的吗

**Comment by new4u** [comment]
今天克隆，每一步都按照readme里的执行

**Comment by ody5sey** [comment]
全程都是采用的都是一个账户，中途没有切换账户吧 

执行source ~/.bashrc的结果看看

**Comment by new4u** [comment]
> 全程都是采用的都是一个账户，中途没有切换账户吧 执行source ~/.bashrc的结果看看
> […](#)

什么都么有发生啊。都是一个账户kali，用了sudo

**Comment by ody5sey** [comment]
你可以用root账户试试

**Comment by new4u** [comment]
没有开root

**Comment by ody5sey** [comment]
你可以新建root账试试

**Comment by new4u** [comment]
用offsec专用 的kali 2018可以不?

**Comment by ody5sey** [comment]
可以

**Comment by new4u** [comment]
Warning: Python 3.8.1 was not found on your system...
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
run.sh: line 23: docker: command not found
run.sh: line 24: docker: command not found
run.sh: line 25: docker: command not found
run.sh: line 26: docker: command not found
run.sh: line 27: docker: command not found
run.sh: line 28: docker: command not found
run.sh: line 31: docker: command not found
run.sh: line 35: docker: command not found
run.sh: line 38: docker: command not found
OK

**Comment by ody5sey** [comment]
你把bash run.sh执行的截图发我

**Comment by new4u** [comment]
我本地是python3.6.6， 虚拟环境pipenv可以装3.6的吗？
提示虚拟环境都没好

**Comment by ody5sey** [comment]
这个我不清楚 你把执行bash run.sh的截图发我 我帮你看看

**Comment by new4u** [comment]
root@kali:~/Voyager# bash run.sh
OK
Hit:1 https://download.docker.com/linux/debian buster InRelease 
Hit:2 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2321 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  docker-ce-cli:amd64

E: Package 'docker-ce' has no installation candidate
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
fatal: destination path '/root/.pyenv' already exists and is not an empty directory.
run.sh: line 16: pyenv: command not found
run.sh: line 17: pyenv: command not found
Requirement already satisfied: pipenv in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: certifi in /usr/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/local/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: typing; python_version < "3.5" in /usr/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: filelock<4,>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: distlib<1,>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: appdirs<2,>=1.4.3 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: importlib-resources<2,>=1.0; python_version < "3.7" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: contextlib2<1,>=0.6.0; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/lib/python2.7/dist-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv->pipenv)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python2.7/dist-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv->pipenv)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv->pipenv)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/lib/python2.7/dist-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv->pipenv)
Warning: Your Pipfile requires python_version 3.8.1, but you are using 3.6.6 (/root/.local/share/v/V/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (374c0a)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 19/19 — 00:00:10
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
run.sh: line 23: docker: command not found
run.sh: line 24: docker: command not found
run.sh: line 25: docker: command not found
run.sh: line 26: docker: command not found
run.sh: line 27: docker: command not found
run.sh: line 28: docker: command not found
run.sh: line 31: docker: command not found
run.sh: line 35: docker: command not found
run.sh: line 38: docker: command not found
OK

**Comment by ody5sey** [comment]
你是不是删除run.sh的内容了

**Comment by new4u** [comment]
怎么删除？！

**Comment by ody5sey** [comment]
你去用kali2020版试试吧，你这个组件好像有问题

**Comment by new4u** [comment]
我之前就是用的kali2020啊

**Comment by ody5sey** [comment]
我看看2020的错误

**Comment by new4u** [comment]
2020运行bash run.sh
没有任何提示

**Comment by ody5sey** [comment]
你还原一下在执行看看

**Comment by new4u** [comment]
我没有做备份镜像 怎么还原呢

**Comment by ody5sey** [comment]
重装
