### ISSUE TITLE
扫描端口报错

### ISSUE THREAD

**Issue by hanxiansheng26** [ody5sey/Voyager#27]
**是否使用了最新代码**
是

**Bug描述**
清晰而简洁的Bug描述（必写）
扫描端口报错

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.8.1]（必写）
centos7
pthon3.8.2
 
**如何复现**
复现步骤（必写,请提交web界面截图和console截图）
![image](https://user-images.githubusercontent.com/38833353/77824211-f6739300-713b-11ea-9b6e-52dd14025509.png)

**报错文本**
复制完整的报错文本（必写）
113.68.154.124 - - [28/Mar/2020 19:25:18] "POST /ports_controllers HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Voyager/app/blueprint/__init__.py", line 17, in decorated_function
    return func(*args, **kwargs)
  File "/root/Voyager/app/blueprint/views/ports.py", line 270, in ports_controllers
    return jsonify(result, safe=False)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/json/__init__.py", line 363, in jsonify
    raise TypeError("jsonify() behavior undefined when passed both args and kwargs")
TypeError: jsonify() behavior undefined when passed both args and kwargs
113.68.154.124 - - [28/Mar/2020 19:25:20] "POST /ports_controllers HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Voyager/app/blueprint/__init__.py", line 17, in decorated_function
    return func(*args, **kwargs)
  File "/root/Voyager/app/blueprint/views/ports.py", line 270, in ports_controllers
    return jsonify(result, safe=False)
  File "/root/.local/share/virtualenvs/Voyager-rmEUjRZG/lib/python3.8/site-packages/flask/json/__init__.py", line 363, in jsonify
    raise TypeError("jsonify() behavior undefined when passed both args and kwargs")
TypeError: jsonify() behavior undefined when passed both args and kwargs
175.155.179.10 - - [28/Mar/2020 19:49:04] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00+&à\x00\x00\x00\x00\x00Cookie:')
175.155.179.10 - - [28/Mar/2020 19:49:04] "+&àCookie: mstshash=hello" HTTPStatus.BAD_REQUEST -
175.155.179.10 - - [28/Mar/2020 20:18:48] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00+&à\x00\x00\x00\x00\x00Cookie:')
175.155.179.10 - - [28/Mar/2020 20:18:48] "+&àCookie: mstshash=hello" HTTPStatus.BAD_REQUEST -

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**Comment by ody5sey** [comment]
我提交了一次代码更新，重新安装试试
