### ISSUE TITLE
添加任务之后终端窗口报错requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

### ISSUE THREAD

**Issue by Roywaller** [ody5sey/Voyager#28]
**是否使用了最新代码**
是

**Bug描述**
添加任务之后终端窗口报错

**运行环境**
 - 系统：Vmware kali 2020
 - Python版本：[例如3.8.1]（必写）
3.8.2
 
**如何复现**
复现步骤（必写,请提交web界面截图和console截图）
![image](https://user-images.githubusercontent.com/12166398/78201072-413a3580-74c3-11ea-935c-089ae1bcb694.png)
![image](https://user-images.githubusercontent.com/12166398/78201092-4e572480-74c3-11ea-91d8-afd86c61733a.png)

**报错文本**
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/js/xadmin.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/css/font.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/lib/layui/layui.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/css/xadmin.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/css/theme1.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/lib/layui/css/layui.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/lib/layui/lay/modules/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 200 -                                                                                       
127.0.0.1 - - [01/Apr/2020 20:58:20] "GET /welcome HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:26] "GET /domain_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:26] "GET /static/css/xadmin.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:27] "GET /domain_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:31] "POST /domains_controllers HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:32] "GET /domain_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/css/xadmin.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/css/font.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/layui.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/js/xadmin.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/css/layui.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/lay/modules/laydate.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 304 -                                                                                       
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/lay/modules/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/lay/modules/form.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/css/modules/laydate/default/laydate.css?v=5.0.9 HTTP/1.1" 304 -                                                                                   
127.0.0.1 - - [01/Apr/2020 20:58:33] "GET /static/lib/layui/lay/modules/element.js HTTP/1.1" 304 -
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/Tools/Voyager/app/lib/core/agent.py", line 78, in subdomain_scan
    contain = DOCKER_CLIENT.containers.run("ap0llo/oneforall:0.0.9", [uid], remove=True, detach=True,
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/models/containers.py", line 802, in run
    container = self.create(image=image, command=command,
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/container.py", line 440, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/client.py", line 289, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/css/font.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/css/xadmin.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/css/login.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/lib/layui/layui.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/lib/layui/css/layui.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/images/bg.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/css/login.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/images/aiwrap.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/lib/layui/lay/modules/form.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 20:59:49] "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 200 -                                                                                       
127.0.0.1 - - [01/Apr/2020 21:00:14] "GET /domain_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:00:14] "GET /static/lib/layui/css/modules/layer/default/icon.png HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:00:14] "GET /static/lib/layui/css/modules/layer/default/loading-1.gif HTTP/1.1" 304 -                                                                                           
127.0.0.1 - - [01/Apr/2020 21:01:16] "POST /domains_controllers HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:20] "GET /domain_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:24] "POST /domains_controllers HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/layui.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/js/xadmin.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/css/font.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/css/xadmin.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/css/theme1.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/css/layui.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /welcome HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/lay/modules/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 304 -                                                                                       
127.0.0.1 - - [01/Apr/2020 21:01:28] "GET /static/lib/layui/lay/modules/element.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:01:32] "GET /domain_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:36] "GET /port_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:37] "GET /ports_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:41] "POST /ports_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:46] "GET /dir_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:01:48] "GET /dirs_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:02:05] "POST /dirs_add HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:02:07] "POST /dirs_controllers HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /dir_lists HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/css/font.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/css/xadmin.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/js/xadmin.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/layui.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/css/layui.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/lay/modules/laydate.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/lay/modules/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 304 -                                                                                       
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/lay/modules/form.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2020 21:02:08] "GET /static/lib/layui/css/modules/laydate/default/laydate.css?v=5.0.9 HTTP/1.1" 304 -                                                                                   
Exception in thread Thread-77:
Traceback (most recent call last):
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/kali/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/Tools/Voyager/app/lib/core/agent_dir.py", line 354, in thread_start
    app.dir_scan(info)
  File "/home/kali/Desktop/Tools/Voyager/app/lib/core/agent_dir.py", line 192, in dir_scan
    contain = DOCKER_CLIENT.containers.run("ap0llo/dirsearch:0.3.9", [target], detach=True,
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/models/containers.py", line 802, in run
    container = self.create(image=image, command=command,
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/container.py", line 440, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/client.py", line 289, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/kali/.local/share/virtualenvs/Voyager-bz1Vz8Ip/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**Comment by ody5sey** [comment]
你这是典型的mongo连接错误，重装一下吧

**Comment by Roywaller** [comment]
重装了两次才解决。。。总是到docker pull mongo的时候出问题 其他都没事
