### ISSUE TITLE
全C段端口扫描时抛出错误

### ISSUE THREAD

**Issue by mux1ng** [ody5sey/Voyager#29]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
全C段端口扫描时抛出错误
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.8.1]（必写）
ubuntu18.04
 python3.8.3
**如何复现**
复现步骤（必写,请提交web界面截图和console截图）
端口扫描 选择C段扫描 端口1-65535
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
121.237.195.132 - - [02/Apr/2020 00:12:01] "POST /ports_controllers HTTP/1.1" 200 -
    self.run()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

**报错文本**
复制完整的报错文本（必写）
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
121.237.195.132 - - [02/Apr/2020 00:12:01] "POST /ports_controllers HTTP/1.1" 200 -
    self.run()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**Comment by ody5sey** [comment]
报错内容不全呀，应该很长的一段吧

**Comment by mux1ng** [comment]
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
121.237.195.132 - - [02/Apr/2020 00:12:01] "POST /ports_controllers HTTP/1.1" 200 -
    self.run()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: ports_scan() takes 1 positional argument but 2 were given
就这么多，应该是ports_scan函数定义的时候只有一个参数
/root/Voyager/app/blueprint/views/ports.py第235行传了两个进去

**Comment by ody5sey** [comment]
OK了 我提交更新了
