### ISSUE TITLE
端口扫描结果导出时500错误

### ISSUE THREAD

**Issue by mux1ng** [ody5sey/Voyager#31]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
端口扫描结果导出时500错误
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.8.1]（必写）
ubuntu18.04
python3.8.2
 
**如何复现**
复现步骤（必写,请提交web界面截图和console截图）
主域名huazhu.com 单目标全端口扫描，导出时500错误

**报错文本**
复制完整的报错文本（必写）
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Voyager/app/blueprint/__init__.py", line 17, in decorated_function
    return func(*args, **kwargs)
  File "/root/Voyager/app/blueprint/views/ports.py", line 284, in ports_controllers
    for i in ports:
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/cursor.py", line 1093, in _refresh
    self.__send_message(g)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/cursor.py", line 953, in __send_message
    response = client._run_operation_with_response(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1342, in _run_operation_with_response
    return self._retryable_read(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1334, in _cmd
    return server.run_operation_with_response(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/server.py", line 128, in run_operation_with_response
    docs = unpack_res(reply, operation.cursor_id,
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/cursor.py", line 1029, in _unpack_response
    return response.unpack_response(cursor_id, codec_options, user_fields,
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pymongo/message.py", line 1590, in unpack_response
    return bson._decode_all_selective(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/bson/__init__.py", line 1098, in _decode_all_selective
    return decode_all(data, codec_options)
bson.errors.InvalidBSON: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**Comment by ody5sey** [comment]
这是你们公司的地址??

**Comment by mux1ng** [comment]
不是啊 补天专属厂商

**Comment by nmapq** [comment]
大佬，更新一下群聊二维码呗
