### ISSUE TITLE
运行manager.py时报错

### ISSUE THREAD

**Issue by weidong7777777** [ody5sey/Voyager#8]
python3 manager.py 
Traceback (most recent call last):
  File "manager.py", line 1, in <module>
    from app import create_app
  File "/root/桌面/Voyager-master/app/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by ody5sey** [comment]
我正在迭代新版本，请稍后

**Comment by weidong7777777** [comment]
必须要使用3.8.1嘛我这安装一直报错 我是3.6.5

**Comment by ody5sey** [comment]
安装教程和安装脚本已经更新完成，请重新安装一次，尽量建议3.8.1，是我的开发版本

**Comment by weidong7777777** [comment]
好谢谢 我再去试试

**Comment by weidong7777777** [comment]
提示完下载python 然后安装后报错
Warning: Python 3.8.1 was not found on your system...
Would you like us to install CPython 3.8.1 with pyenv? [Y/n]: 
提示我安装CPython

**Comment by ody5sey** [comment]
请按照BUG REPORT模版重新提交一个issues
<img width="669" alt="截屏2020-03-07下午1 17 27" src="https://user-images.githubusercontent.com/60533474/76137467-3cc35e00-6078-11ea-8a11-32737e353724.png">
